### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by shihyu** [ina-foss/inaSpeechSegmenter#20]
I use the command line as below
Ina_speech_segmenter.py -i 0021.mp3 -o out/

The 0021.mp3 file download URL below.
https://www.mediafire.com/file/krfuk8wshq5jr2o/0021.mp3/file

May I know why I got this error message?

`Using TensorFlow backend.
2019-10-11 21:54:43.913936: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3392295000 Hz
2019-10-11 21:54:43.914400: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f69cdadd70 executing computations on platform Host. Devices:
2019-10-11 21:54:43.914417: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
/home/shihyu/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py:384: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
/home/shihyu/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py:384: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
processing file 1/1: 0021.mp3
Traceback (most recent call last):
  File "/home/shihyu/anaconda3/bin/ina_speech_segmenter.py", line 63, in <module>
    seg2csv(seg(e), '%s/%s.csv' % (odir, base))
  File "/home/shihyu/anaconda3/lib/python3.7/site-packages/inaSpeechSegmenter/segmenter.py", line 174, in __call__
    return self.segmentwav(tmpwav)
  File "/home/shihyu/anaconda3/lib/python3.7/site-packages/inaSpeechSegmenter/segmenter.py", line 148, in segmentwav
    data21, finite = _get_patches(mspec[:, :21], 68, 2)
  File "/home/shihyu/anaconda3/lib/python3.7/site-packages/inaSpeechSegmenter/segmenter.py", line 69, in _get_patches
    data = vaw(mspec, (w,h), step=step)
  File "/home/shihyu/anaconda3/lib/python3.7/site-packages/skimage/util/shape.py", line 240, in view_as_windows
    raise ValueError("`window_shape` is too large")
ValueError: `window_shape` is too large

`

**Comment by DavidDoukhan** [comment]
Dear shihyu,
Thanks for this constructive feedback.

For now, inaSpeechSemgenter requires sound sample of at least 720 milliseconds.
It seems the duration of your sound excerpt is 705 milliseconds, which is too small for being used as it.

A simple short-term workaround for managing such material would be that you manually edit this sound sample to make it last more than 720 milliseconds (you may padd with some 0 at the end of the signal).

On a longer term, I'll do some modifications in my code to do this padding within the software, in order to avoid such inconvenience.
I did downloaded the sound sample you provided me.
May I include it in this repository? If yes, could you provide me more information on its origin/license?
I'm planning to integrate some unittests in this framework, and your sample would fit perfectly.

Kind regards,

**Comment by DavidDoukhan** [comment]
Dear shihyu,
I did small modifications in the code in order to handle small audio excerpts.
Please let me know if these changes suit your needs.
Kind regards,
