### ISSUE TITLE
with which tensorflow version it is compatible with ? unable to import package

### ISSUE THREAD

**Issue by kunalsharmagnome** [ina-foss/inaSpeechSegmenter#30]
Traceback (most recent call last):
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper        
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "Z:\anaconda\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "Z:\anaconda\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Z:\anaconda\lib\site-packages\inaSpeechSegmenter\__init__.py", line 26, in <module>
    from .segmenter import Segmenter, seg2csv
  File "Z:\anaconda\lib\site-packages\inaSpeechSegmenter\segmenter.py", line 31, in <module>
    import keras
  File "Z:\anaconda\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "Z:\anaconda\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "Z:\anaconda\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "Z:\anaconda\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "Z:\anaconda\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "Z:\anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "Z:\anaconda\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "Z:\anaconda\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "Z:\anaconda\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "Z:\anaconda\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "Z:\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper        
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    return load_dynamic(name, filename, file)
  File "Z:\anaconda\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by DavidDoukhan** [comment]
Hi,

inaSpeechSegmenter is supposed to handle severa tensorflow versions, including the latests.
Could your provide me more details on your issue:

* tensorflow version
* cuda version
* nvidia drivers version
* steps used for insaspeechsegmenter installation

**Comment by kunalsharmagnome** [comment]
@DavidDoukhan it working now i made some stupid mistake .
