### ISSUE TITLE
Dockerfile do not work

### ISSUE THREAD

**Issue by hdubey** [ina-foss/inaSpeechSegmenter#43]
Even using the provided docker I am getting below error. Can you please provide requirement.txt for this repo?
: 

Traceback (most recent call last):                                                                       │··············································································································
  File "<stdin>", line 1, in <module>                                                                    │··············································································································
  File "/usr/local/lib/python3.6/dist-packages/inaSpeechSegmenter/__init__.py", line 26, in <module>     │··············································································································
    from .segmenter import Segmenter, seg2csv                                                            │··············································································································
  File "/usr/local/lib/python3.6/dist-packages/inaSpeechSegmenter/segmenter.py", line 31, in <module>    │··············································································································
    import keras                                                                                         │··············································································································
  File "/usr/local/lib/python3.6/dist-packages/keras/__init__.py", line 6, in <module>                   │··············································································································
    'Keras requires TensorFlow 2.2 or higher. '                                                          │··············································································································
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by DavidDoukhan** [comment]
Dear @hdubey,

Thanks for this report. 
I'm currently having holidays without laptop. 
I only have my smartphone which is not suited for debugging my code. 

My feeling concerning the issue you reports is that you should downgrade keras within the dockerfile. My feeling is that up-to-date keras versions require newest versions of tensor flow. I'll have a look at it when coming back from holidays.

Kind regards
