### ISSUE TITLE
Invalid input shape for input Tensor

### ISSUE THREAD

**Issue by Estrangeling** [ina-foss/inaSpeechSegmenter#81]
I am using Windows 10 and your program doesn't work at all. The tutorial is useless. And I am no fool, check my [Stack](https://stackoverflow.com/users/16383578) [Exchange](https://superuser.com/users/1250181/) [profiles](https://codereview.stackexchange.com/users/234107/) to see what I can do with computers.

I am using Python 3.11.3 and just downloaded inaSpeechSegmenter  using pip. I haven't installed any other libraries in this Python installation (I mainly use Python 3.10)

I followed the useless tutorial as is, and it doesn't work at all.

```
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from inaSpeechSegmenter import Segmenter
2024-03-14 00:01:20.413131: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-14 00:01:27.321084: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
>>> seg = Segmenter(ffmpeg="D:/ffmpeg/ffmpeg.exe")
C:\Python311\Lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2024-03-14 00:01:48.032975: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:absl:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:absl:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
>>> seg(r"D:\tts_test\tts_models~en~vctk~vits,p225.mp3")
C:\Python311\Lib\site-packages\inaSpeechSegmenter\segmenter.py:80: RuntimeWarning: invalid value encountered in subtract
  data = (data - np.mean(data, axis=1).reshape((len(data), 1))) / np.std(data, axis=1).reshape((len(data), 1))
C:\Python311\Lib\site-packages\numpy\core\_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\inaSpeechSegmenter\segmenter.py", line 294, in __call__
    return self.segment_feats(mspec, loge, difflen, start_sec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\inaSpeechSegmenter\segmenter.py", line 268, in segment_feats
    lseg = self.vad(mspec, lseg, difflen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\inaSpeechSegmenter\segmenter.py", line 162, in __call__
    rawpred = self.nn.predict(batch, batch_size=self.batch_size, verbose=2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python311\Lib\site-packages\keras\src\models\functional.py", line 274, in _adjust_input_rank
    raise ValueError(
ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(32, 68, 21), dtype=float32). Expected shape (None, None, 68, 21), but input has incompatible shape (32, 68, 21)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(32, 68, 21), dtype=float32)
  • training=False
  • mask=None
>>>
```

```
ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(32, 68, 21), dtype=float32). Expected shape (None, None, 68, 21), but input has incompatible shape (32, 68, 21)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(32, 68, 21), dtype=float32)
  • training=False
  • mask=None
```

I could try to resolve this issue if I check the bugs in your source code, but I have fixed so many poorly written scripts of others that I don't want to.

And your Segmentation class doesn't expose any way to adjust the shape parameter. You need to fix this.

**Comment by DavidDoukhan** [comment]
This request lacks benevolence. I remind you that this is an open-source software provided for free. Due to the tone used, I will not respond to this request.
FYI : i HATE WINDOWS

**Comment by elieobeid7** [comment]
@Estrangeling Did you have to phrase your question like that? Tell me Did you have to? What did you gain? 

1. Your problem wasn't solved
2. You pissed off the maintainers, so they won't solve the problem
3. All windows users, including me, we now have to find a solution on our own, because as soon as we open a ticket, the maintainers will remember your ticket and close the ticket out of spite.
4.  Did you solve the issue?
5. The maintainer have every right to answer you the way he did, and to hate on Windows, just yesterday, they released "Recall AI", a spyware essentially
6. This library is the best library out there for audio segmentation, if you believe otherwise please share your alternative


In any case, this is just a warning, the library works, at least for me.
