### ISSUE TITLE
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

### ISSUE THREAD

**Issue by tgrushka** [ina-foss/inaSpeechSegmenter#83]
M1 MacBook Pro
macOS Sonoma 14.5
Python 3.12.3
Clean venv with only this package

```
ina_speech_segmenter.py -i ~/Video\ Projects/5280+\ Senior\ Chorales/Parker\ 2024-04-14.mp3 -o test/ -g false
```

```
/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/keras/src/layers/reshaping/reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
batch_processing 1 files
1/1 [('test/Parker 2024-04-14.csv', 0, 'ok')]
Traceback (most recent call last):
  File "/Users/tom/speech_segmenter/.venv/bin/ina_speech_segmenter.py", line 80, in <module>
    seg.batch_process(input_files, output_files, verbose=True, output_format=args.export_format)
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/inaSpeechSegmenter/segmenter.py", line 313, in batch_process
    lseg = self.segment_feats(mspec, loge, difflen, 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/inaSpeechSegmenter/segmenter.py", line 248, in segment_feats
    for lab, start, stop in _binidx2seglist(_energy_activity(loge, self.energy_ratio)[::2]):
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/inaSpeechSegmenter/segmenter.py", line 54, in _energy_activity
    return viterbi_decoding(pred2logemission(raw_activity),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/pyannote/algorithms/utils/viterbi.py", line 172, in viterbi_decoding
    emission = _update_emission(emission, consecutive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/pyannote/algorithms/utils/viterbi.py", line 86, in _update_emission
    return np.vstack(
           ^^^^^^^^^^
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/speech_segmenter/.venv/lib/python3.12/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
```

```
pip freeze
absl-py==2.1.0
astunparse==1.6.3
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
contourpy==1.2.1
cycler==0.12.1
docopt==0.6.2
flatbuffers==24.3.25
fonttools==4.53.0
gast==0.5.4
google-pasta==0.2.0
grpcio==1.64.1
h5py==3.11.0
idna==3.7
imageio==2.34.1
inaSpeechSegmenter==0.7.6
joblib==1.4.2
keras==3.3.3
kiwisolver==1.4.5
lazy_loader==0.4
libclang==18.1.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdurl==0.1.2
ml-dtypes==0.3.2
munkres==1.1.4
namex==0.0.8
networkx==3.3
numpy==1.26.4
opt-einsum==3.3.0
optree==0.11.0
packaging==24.1
pandas==2.2.2
pillow==10.3.0
protobuf==4.25.3
pyannote.algorithms==0.8
pyannote.core==5.0.0
pyannote.parser==0.8
pycparser==2.22
Pygments==2.18.0
pyparsing==3.1.2
Pyro4==4.82
pytextgrid==0.1.4
python-dateutil==2.9.0.post0
pytz==2024.1
requests==2.32.3
rich==13.7.1
scikit-image==0.23.2
scikit-learn==1.5.0
scipy==1.13.1
serpent==1.41
setuptools==70.0.0
six==1.16.0
sortedcollections==2.1.0
sortedcontainers==2.4.0
soundfile==0.12.1
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
termcolor==2.4.0
threadpoolctl==3.5.0
tifffile==2024.5.22
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.1
Werkzeug==3.0.3
wheel==0.43.0
wrapt==1.16.0
xarray==2024.6.0
```

**Comment by DavidDoukhan** [comment]
Dear @tgrushka ,

It's seems you're using an old version of inaspeechsegmenter (inaSpeechSegmenter==0.7.6) with a known bug due to dependencies update.

The current version available with pip is 0.7.8 .
Could you retry using the current version ? 
In case of issues with pypi installer, please try installing from sources and let me know about the behaviors.

Kind regards,
